spring:
  application:
    name: CareerCoachDemo

  datasource:
    url: jdbc:mysql://localhost:3306/career_coach?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  h2:
    console:
      enabled: false

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.puregxl.careercoachdemo.model
  configuration:
    map-underscore-to-camel-case: true

# Custom Application Properties
app:
  cal:
    booking-base-url: https://cal.com/team/career-coach/30min
    cal-base-url: https://cal.com/chau-chau-smfbef/30min
